import { expect, test } from '@playwright/test';
import { newStore } from '../../src/shared/merge';

test('two devices merge offline captures, persist through reload, and honor deletion', async ({ browser }) => {
  const phone = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const desktop = await browser.newContext();
  const a = await phone.newPage(); const b = await desktop.newPage();
  const suffix = crypto.randomUUID().slice(0, 8);
  const first = `offline thought ${suffix}`; const second = `desktop thought ${suffix}`;
  await a.goto('/'); await b.goto('/');
  await expect(a.getByRole('textbox', { name: 'Capture a thought' })).toBeEnabled();
  await expect(b.getByRole('textbox', { name: 'Capture a thought' })).toBeEnabled();
  await a.evaluate(async () => { await navigator.serviceWorker.ready; });
  await a.reload();
  await expect(a.getByRole('textbox', { name: 'Capture a thought' })).toBeEnabled();
  await phone.setOffline(true);
  await a.getByRole('textbox', { name: 'Capture a thought' }).fill(first);
  await a.getByRole('button', { name: 'Save dump', exact: true }).click();
  await expect(a.getByRole('article').getByText(first, { exact: true })).toHaveCount(1);
  await expect(a.getByRole('status')).toContainText('Offline · saved here');
  await a.reload();
  await expect(a.getByRole('article').getByText(first, { exact: true })).toBeVisible();
  await b.getByRole('textbox', { name: 'Capture a thought' }).fill(second);
  await b.getByRole('button', { name: 'Save dump', exact: true }).click();
  await phone.setOffline(false);
  await expect(b.getByRole('article').getByText(first, { exact: true })).toBeVisible({ timeout: 20_000 });
  await expect(a.getByRole('article').getByText(second, { exact: true })).toBeVisible();
  await expect(b.getByRole('article').getByText(first, { exact: true })).toHaveCount(1);
  await phone.setOffline(true);
  await b.getByRole('button', { name: `Actions: ${first}`, exact: true }).click();
  await b.getByRole('menuitem', { name: 'Remove dump' }).click();
  await expect(b.getByRole('article').getByText(first, { exact: true })).toHaveCount(0);
  await phone.setOffline(false);
  await expect(a.getByRole('article').getByText(first, { exact: true })).toHaveCount(0);
  await phone.close(); await desktop.close();
});

test('prefix filing, search, export and additive restore work', async ({ page }) => {
  const text = `Reading lamp ${crypto.randomUUID().slice(0, 8)} #home`;
  await page.goto('/');
  await page.getByRole('textbox', { name: 'Capture a thought' }).fill(`!buy ${text}`);
  await page.getByRole('button', { name: 'Save dump', exact: true }).click();
  await page.getByRole('navigation').getByRole('link', { name: /^Buy/ }).click();
  await expect(page.getByRole('article').getByText(text, { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Search your space' }).click();
  await page.getByRole('combobox', { name: 'Search dumps' }).fill(text);
  await page.getByRole('option').filter({ hasText: text }).click();
  await expect(page.getByRole('article').getByText(text, { exact: true })).toBeVisible();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('button', { name: 'Export backup' }).click();
  const download = await downloadPromise;
  const path = await download.path();
  expect(path).toBeTruthy();
  await page.locator('input[type="file"]').setInputFiles(path!);
  await expect(page.getByText('0 dumps restored. Existing items were kept.')).toBeVisible();
});

test('HTTP sync works with WebSockets blocked and rejects invalid requests', async ({ browser, request }) => {
  const aContext = await browser.newContext(); const bContext = await browser.newContext();
  for (const context of [aContext, bContext]) await context.routeWebSocket('**/api/events', (ws) => ws.close());
  const a = await aContext.newPage(); const b = await bContext.newPage();
  await a.goto('/'); await b.goto('/');
  const text = `HTTP fallback ${crypto.randomUUID().slice(0, 8)}`;
  await a.getByRole('textbox', { name: 'Capture a thought' }).fill(text);
  await a.getByRole('button', { name: 'Save dump', exact: true }).click();
  await expect(b.getByRole('article').getByText(text, { exact: true })).toBeVisible({ timeout: 22_000 });
  const rejected = await request.post('/api/sync', { headers: { Origin: 'https://evil.example' }, data: {} });
  expect(rejected.status()).toBe(403);
  const malformed = await request.post('/api/sync', { headers: { Origin: 'http://127.0.0.1:6192' }, data: { version: 999, content: [] } });
  expect(malformed.status()).toBe(400);
  const good = await request.post('/api/sync', { headers: { Origin: 'http://127.0.0.1:6192' }, data: { version: 1, content: newStore().getMergeableContent() } });
  expect(good.status()).toBe(200);
  await aContext.close(); await bContext.close();
});

test('mobile layout fits and navigation is usable', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  const page = await context.newPage();
  await page.goto('/');
  await expect(page.getByRole('textbox', { name: 'Capture a thought' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await page.getByRole('navigation').getByRole('link', { name: /^Ideas/ }).click();
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Ideas');
  await context.close();
});

test('custom lists, filing, renaming and board order sync and survive reload', async ({ browser }) => {
  const aContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const bContext = await browser.newContext();
  const a = await aContext.newPage(); const b = await bContext.newPage();
  const name = `Books-${crypto.randomUUID().slice(0, 6)}`;
  const thought = `Read something slow ${name}`;
  await a.goto('/'); await b.goto('/board');
  await a.getByRole('button', { name: 'Create new list' }).click();
  await a.getByRole('textbox', { name: 'List name' }).fill(name);
  await a.getByRole('button', { name: 'Create list', exact: true }).click();
  await expect(a.getByRole('heading', { level: 1 })).toHaveText(new RegExp(name));
  await a.getByRole('textbox', { name: 'Capture a thought' }).fill(`!${name.toLowerCase()} ${thought}`);
  await a.getByRole('button', { name: 'Save dump', exact: true }).click();
  await expect(a.getByRole('article').getByText(thought, { exact: true })).toBeVisible();
  await expect(b.getByRole('region', { name: `${name} column`, exact: true }).getByText(thought, { exact: true })).toBeVisible({ timeout: 20_000 });
  await a.getByRole('button', { name: 'Edit list', exact: true }).click();
  await a.getByRole('textbox', { name: 'List name' }).fill(`${name} shelf`);
  await a.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(b.getByRole('region', { name: `${name} shelf column`, exact: true })).toBeVisible();
  await a.getByRole('navigation').getByRole('link', { name: 'Board', exact: true }).click();
  await expect(a.getByRole('region', { name: `${name} shelf column`, exact: true })).toBeVisible();
  const oldOrder = await a.locator('.board-column h2').allTextContents();
  await a.getByRole('button', { name: `Options for ${name} shelf`, exact: true }).click();
  await a.getByRole('menuitem', { name: 'Move left', exact: true }).click();
  const expected = [...oldOrder];
  const previousIndex = expected.indexOf(`${name} shelf`);
  expected.splice(previousIndex, 1); expected.splice(previousIndex - 1, 0, `${name} shelf`);
  await expect(a.locator('.board-column h2')).toHaveText(expected);
  await expect(b.locator('.board-column h2')).toHaveText(expected);
  await a.reload();
  await expect(a.locator('.board-column h2')).toHaveText(expected);
  await a.screenshot({ path: 'test-results/board-desktop.png', fullPage: true });
  await aContext.close(); await bContext.close();
});

test('dialogs center, restore focus, and theme preference survives reload', async ({ page }) => {
  await page.goto('/');
  const search = page.getByRole('button', { name: 'Search your space' });
  await search.click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toBeVisible();
  await expect(page.getByRole('combobox', { name: 'Search dumps' })).toBeFocused();
  const centered = await dialog.evaluate((element) => {
    const rect = element.getBoundingClientRect();
    return Math.abs(rect.x + rect.width / 2 - innerWidth / 2) < 2 && Math.abs(rect.y + rect.height / 2 - innerHeight / 2) < 2;
  });
  expect(centered).toBe(true);
  await page.keyboard.press('Escape');
  await expect(search).toBeFocused();
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('button', { name: 'Dark', exact: true }).click();
  await expect(page.locator('html')).toHaveClass(/dark/);
  await page.keyboard.press('Escape');
  await page.reload();
  await expect(page.locator('html')).toHaveClass(/dark/);
  await expect(page.getByRole('textbox', { name: 'Capture a thought' })).toBeEnabled();
  await page.screenshot({ path: 'test-results/inbox-dark.png', fullPage: true });
});

test('mobile board, sheet focus, reduced motion, and dialog fit', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
  const page = await context.newPage();
  await page.goto('/board');
  await expect(page.getByRole('heading', { name: /Your board/ })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  const trigger = page.getByRole('button', { name: 'Open navigation' });
  await trigger.click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(trigger).toBeFocused();
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  const bounds = await page.getByRole('dialog').boundingBox();
  expect(bounds).not.toBeNull();
  expect(bounds!.x).toBeGreaterThanOrEqual(0);
  expect(bounds!.y).toBeGreaterThanOrEqual(0);
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390);
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(844);
  await page.screenshot({ path: 'test-results/settings-mobile.png', fullPage: true });
  await page.keyboard.press('Escape');
  await page.screenshot({ path: 'test-results/board-mobile.png', fullPage: true });
  await context.close();
});

test('marketing is separate from notebook initialization and preserves the original logo', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  const apiRequests: string[] = [];
  page.on('request', (request) => { if (new URL(request.url()).pathname.startsWith('/api/')) apiRequests.push(request.url()); });
  await page.goto('/marketing');
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Your mind is for ideas.');
  await expect(page.locator('.brand-mark').first()).toHaveCSS('background-color', 'rgb(216, 238, 121)');
  expect(await page.evaluate(() => indexedDB.databases())).toEqual([]);
  expect(apiRequests).toEqual([]);
  await page.screenshot({ path: 'test-results/marketing-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/marketing-mobile.png', fullPage: true });
  await context.close();
});
