import { ArrowRight, ArrowUp, Asterisk, Check, Cloud, Inbox, Layers3, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Brand } from './components/Brand';
import { Button } from './components/ui/button';

export default function Marketing() {
  return <div className="marketing"><header className="marketing-nav"><Link to="/marketing" aria-label="About Dump"><Brand /></Link><a href="#how-it-works" className="marketing-about">A little less on your mind</a><Button asChild variant="outline"><Link to="/">Open your space<ArrowRight /></Link></Button></header>
    <main><section className="marketing-hero"><div className="marketing-eyebrow"><span />FOR THOUGHTS THAT NEED SOMEWHERE TO GO</div><h1>Your mind is for ideas.<br /><span>Not holding onto them.</span></h1><p>The book someone mentioned. A half-formed idea. That link for later.<br className="desktop-label" /> Put it all in Dump. Give it a home when you feel like it.</p><Button asChild size="lg"><Link to="/">A little more headspace<ArrowRight /></Link></Button><small>Capture first. Organize optionally.</small></section>
      <section className="marketing-preview" aria-label="Illustration of Dump with example thoughts"><div className="preview-top"><span><Asterisk size={18} />My little corner</span><Search size={16} /></div><div className="preview-body"><div className="preview-capture"><Asterisk size={24} /><span>What’s on your mind?</span><ArrowUp size={20} /></div><div className="preview-columns">{[{ name: 'Inbox', color: '#a799b8', items: ['A Sunday with no plans.', 'What if the best ideas happen on a walk?'] }, { name: 'Ideas', color: '#9b84d6', items: ['A tiny reading nook by the window', 'Make something just for the fun of it.'] }, { name: 'For later', color: '#849c74', items: ['The little bookshop on the corner', 'That film everyone keeps talking about'] }].map((column) => <div key={column.name}><h2><span className="list-dot" style={{ background: column.color }} />{column.name}<span>2</span></h2>{column.items.map((item) => <div className="preview-card" key={item}>{item}<small>Saved for a quieter moment</small></div>)}</div>)}</div></div><div className="preview-bottom"><Check size={12} />Example thoughts · your space starts empty</div></section>
      <section className="marketing-features" id="how-it-works"><div><Inbox size={23} /><span>01 — LET IT OUT</span><h2>One box. Anything goes.</h2><p>Thoughts, links, to-dos, or a sentence that isn’t quite an idea yet. No form to fill out. Just get it down.</p></div><div><Layers3 size={23} /><span>02 — MAKE A LITTLE ROOM</span><h2>A place, at your pace.</h2><p>Leave things in your inbox or make your own lists. See them side by side, arranged the way your mind works.</p></div><div><Cloud size={23} /><span>03 — COME BACK TO IT</span><h2>Here when you need it.</h2><p>Search for the thought you almost forgot. Capture offline on a previously loaded device, and sync when you’re back.</p></div></section>
      <section className="marketing-outro"><Asterisk size={45} /><h2>Less to carry.<br />More room to think.</h2><Button asChild><Link to="/">Open Dump<ArrowRight /></Link></Button><p>This is a personal project. The current deployment is public.</p></section>
    </main><footer className="marketing-footer"><Brand /><span>Out of your head. Into your space.</span><Link to="/">Back to your space ↗</Link></footer>
  </div>;
}
